name: Daily Push Notification

on:
  schedule:
    - cron: '0 17 * * *'  # เที่ยงคืนเวลาไทย (UTC+7)
  workflow_dispatch:      # สำหรับกดรันเองได้ด้วย

jobs:
  send-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install node-fetch

      - name: Run push script
        run: node send-push.js
