name: Daily Push Notification

on:
  schedule:
    - cron: '0 17 * * *'   # 17 UTC = 00:00 Thailand time (GMT+7)
  workflow_dispatch:

permissions:
  contents: read
jobs:
  send-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Run push script
        run: node send-push.mjs
